"""Setting up

Revision ID: b3fea8ceaafe
Revises: 
Create Date: 2026-02-23 18:50:33.927443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3fea8ceaafe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('pass_hash', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('student', 'company', 'admin', name='user_role'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_id'), ['id'], unique=False)

    op.create_table('company',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=100), nullable=True),
    sa.Column('website', sa.String(length=100), nullable=True),
    sa.Column('approval', sa.Enum('pending', 'approved', 'rejected', name='cmp_approval_status'), nullable=False),
    sa.Column('is_blacklisted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('company_id')
    )
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_company_company_name'), ['company_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_company_user_id'), ['user_id'], unique=False)

    op.create_table('student',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('branch', sa.String(length=100), nullable=True),
    sa.Column('cgpa', sa.Float(), nullable=False),
    sa.Column('grad_year', sa.Integer(), nullable=True),
    sa.Column('resume_path', sa.String(length=200), nullable=True),
    sa.Column('approval', sa.Enum('pending', 'approved', 'rejected', name='std_approval_status'), nullable=False),
    sa.Column('is_blacklisted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('student_id')
    )
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_cgpa'), ['cgpa'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_full_name'), ['full_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_user_id'), ['user_id'], unique=False)

    op.create_table('drive',
    sa.Column('drive_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('job_role', sa.String(length=100), nullable=False),
    sa.Column('job_desc', sa.Text(), nullable=True),
    sa.Column('cgpa_criteria', sa.Float(), nullable=True),
    sa.Column('branch_criteria', sa.String(length=100), nullable=True),
    sa.Column('ctc', sa.Integer(), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('open', 'closed', name='drive_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('approval', sa.Enum('pending', 'approved', 'rejected', name='drive_approval_status'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.company_id'], ),
    sa.PrimaryKeyConstraint('drive_id')
    )
    with op.batch_alter_table('drive', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_drive_cgpa_criteria'), ['cgpa_criteria'], unique=False)
        batch_op.create_index(batch_op.f('ix_drive_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_drive_ctc'), ['ctc'], unique=False)
        batch_op.create_index(batch_op.f('ix_drive_drive_id'), ['drive_id'], unique=False)

    op.create_table('application',
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('drive_id', sa.Integer(), nullable=False),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('applied', 'shortlisted', 'selected', 'rejected', name='application_status'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['drive_id'], ['drive.drive_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.student_id'], ),
    sa.PrimaryKeyConstraint('app_id'),
    sa.UniqueConstraint('student_id', 'drive_id', name='unique_appn')
    )
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_application_app_id'), ['app_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_application_drive_id'), ['drive_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_application_student_id'), ['student_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_application_student_id'))
        batch_op.drop_index(batch_op.f('ix_application_drive_id'))
        batch_op.drop_index(batch_op.f('ix_application_app_id'))

    op.drop_table('application')
    with op.batch_alter_table('drive', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_drive_drive_id'))
        batch_op.drop_index(batch_op.f('ix_drive_ctc'))
        batch_op.drop_index(batch_op.f('ix_drive_company_id'))
        batch_op.drop_index(batch_op.f('ix_drive_cgpa_criteria'))

    op.drop_table('drive')
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_user_id'))
        batch_op.drop_index(batch_op.f('ix_student_student_id'))
        batch_op.drop_index(batch_op.f('ix_student_full_name'))
        batch_op.drop_index(batch_op.f('ix_student_cgpa'))

    op.drop_table('student')
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_user_id'))
        batch_op.drop_index(batch_op.f('ix_company_company_name'))
        batch_op.drop_index(batch_op.f('ix_company_company_id'))

    op.drop_table('company')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_id'))

    op.drop_table('user')
    # ### end Alembic commands ###
